p8105_hw2_kiu2103
================
Kaveri Uberoy
2025-09-25

Loading in packages we need.

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
library(dplyr)
library(knitr)
```

## Problem 1

Our goal is to merge these into a single data frame using year and month
as keys across datasets.

Cleaning the data in pols-month.csv. Used prez_dem value to create
president variable instead of prez_gop value as prez_gop value is
sometimes 1 and sometimes 2.

``` r
pols_df = 
  read_csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(across(c(year, month, day), as.integer)) |>
  mutate(month = month.name[month]) |>
  mutate(president = if_else(prez_dem == 1, "dem" , "gop")) |>
  select(-prez_gop, -prez_dem) |>
  select(-day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Clean the data in snp.csv using a similar process to the above. Also
removed the day variable here to match pols_df tidying, made changes to
year value to also match pols_df.

``` r
snp_df = 
  read_csv("data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(across(c(year, month, day), as.integer)) |>
  mutate(year = if_else(year > 25, 1900 + year, 2000 + year)) |>
  mutate(month = month.name[month]) |>
  select(-day) |>
  relocate(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Tidying the unemployment data so that it can be merged with the previous
datasets by month and year.

``` r
unemployment_df =
  read_csv("data/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    cols = -year,
    names_to = "month",
    values_to = "unemployment_rate"
  ) |>
  mutate(
    month_num = match(tolower(month), tolower(month.abb)),
    month = month.name[month_num] 
  ) |>
  select(year, month, unemployment_rate)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Join the datasets by left joining snp into pols, and left joining
unemployment into the result.

``` r
pol_eco_fin_merged_df =
  pols_df |>
  left_join(snp_df, by = c("year", "month")) |>
  left_join(unemployment_df, by = c("year", "month"))
```

Write a short paragraph about these datasets. Explain briefly what each
dataset contained, and describe the resulting dataset (e.g. give the
dimension, range of years, and names of key variables).

The dataset construction involved merging three different csv files
containing political, economic, and financial data into one tidy
dataset, The pols\_-month_df dataset includes monthly counts of
Democratic and Republican governors, senators, and representatives,
along with the party of the president. The mon date variable was split
into year and month, and a new president variable was created using the
value of the prez_dem (if equal to 1, president column = dem, if equal
to zero then gop). The snp_df dataset provides the Standard & Poor’s
stock market index (S&P) closing values for specific dates. The date
column was transformed into year and month so that we could merge with
the other datasets later. The unemployment_df dataset, which contains
unemployment rates for each date (month/year) originally in a wide
format with months as column headers, was pivoted to a long format for
compatibility. Month abbreviations were converted to full names to align
with the other datasets for merging as well. The resulting dataset,
pol_eco_fin_merged_df (left joined by date values) combines all three
sources and includes 822 observations with 11 variables like year,
month, president, counts of politicians by party, close (S&P 500 index),
and unemployment. It spans a range of years (January 1947 to June 2015)
from the earliest in pols_df to the latest in snp_df (depending on
overlap). Key variables include president, sen_gop, rep_dem, close, and
unemployment. The dataset is useful to look at politics, economics, and
unemployment data together to compare these different factors.

## Problem 2

Reading and cleaning the Mr. Trash Wheel sheet:

``` r
trashwheel_df =
  read_excel("data/trash_wheel_collection_data.xlsx", 
             sheet = "Mr. Trash Wheel",
             range = "A2:N709") |>
  janitor::clean_names() |>
  mutate(
      sports_balls = as.integer(round(sports_balls)),
      year = as.numeric(year)
    )
```

Importing, cleaning, and organizing the data for Professor Trash Wheel
and Gwynnda, and combining this with the Mr. Trash Wheel dataset to
produce a single tidy dataset.

``` r
professor_trashwheel_df =
  read_excel("data/trash_wheel_collection_data.xlsx", 
             sheet = "Professor Trash Wheel",
             range = "A2:M134") |>
  janitor::clean_names()

gwynnda_trashwheel_df =
  read_excel("data/trash_wheel_collection_data.xlsx", 
             sheet = "Gwynns Falls Trash Wheel",
             range = "A2:L351") |>
  janitor::clean_names()

trashwheels_combined_df = 
  bind_rows(
    trashwheel_df |>
      mutate(
        trash_wheel = "Mr. Trash Wheel"
      ),
    professor_trashwheel_df |>
      mutate(
        trash_wheel = "Professor Trash Wheel"
      ),
    gwynnda_trashwheel_df |>
      mutate(
        trash_wheel = "Gwynnda"
      )
  )
```

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in the resulting dataset, and
give examples of key variables. For available data, what was the total
weight of trash collected by Professor Trash Wheel? What was the total
number of cigarette butts collected by Gwynnda in June of 2022?

Each of the trash_wheel datasets contain information on the amounts of
trash that each trashwheel collected,in weight and volume, when it was
collected, which dumpster it was collected from, and information on the
amounts of specific types of trash it collected (like plastic bottles,
wrappers, sports balls, etc). Each data set also notes how many homes
were powered by the trashwheel that month. The combined dataset,
trashwheels_combined_df contains 1188 observations collected from three
distinct trash wheels: Mr. Trash Wheel, Professor Trash Wheel, and
Gwynnda. Key variables in the combined dataset include the trashwheel
responsible for each row, the weight of trash collected (in tons),
counts of specific items such as cigarette butts, sports balls, and
plastics, as well as time variables like month and year. Professor Trash
Wheel collected a total of 282.26 tons of trash. Meanwhile, Gwynnda
collected 1.812^{4} cigarette butts in June 2022 alone.

## Problem 3

Create a single, well-organized dataset with all the information from
zips and zori datasets, and combine them.

``` r
zips_df = 
  read_csv("data/Zip Codes.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() 
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori_df = 
  read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", na = c("NA", ".", "")) |>
  janitor::clean_names() |>
  pivot_longer(cols = x2015_01_31:x2024_08_31,
               names_to = "date",
               values_to = "zori") |>
  mutate(region_name = as.numeric(region_name)) |>
  mutate(county_name = str_remove(county_name," County")) |>
  rename(county = county_name) |>
  rename(zip_code = region_name)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
joined_zipcode_data =  
  left_join(zips_df, zori_df, by = c("zip_code", "county")) |>
  select(-state, -city, -metro, -region_type, -state_name, -state_fips, -file_date)
```

Briefly describe the resulting tidy dataset. How many total observations
exist? How many unique ZIP codes are included, and how many unique
neighborhoods?

The resulting tidy dataset, joined_zipcode_df, is the zillow data
(zori_df) left joined onto the zipcode data (zips_df) with all the
redundant columns (which all had the same value for every row, like
state, city, metro and so on) removed. Since there were some repeated
zip codes for two different counties, I left joined keeping in mind both
zip code and county instead of zip code alone. Some of the variables in
this data set include the zip code, the neighborhood, the county code,
and the zori data for each case. Total number of observations are 17342.
Number of unique ZIP codes are 320. Number of unique neighborhoods are
43.

Which ZIP codes appear in the ZIP code dataset but not in the Zillow
Rental Price dataset? Using a few illustrative examples discuss why
these ZIP codes might be excluded from the Zillow dataset.

Missing zips:

``` r
missing_zips = zips_df |>
  anti_join(zori_df, by = "zip_code") |>
  select(-state_fips, -file_date)
kable(missing_zips)
```

| county   | county_code | county_fips | zip_code | neighborhood               |
|:---------|:------------|------------:|---------:|:---------------------------|
| Bronx    | 005         |       36005 |    10464 | Southeast Bronx            |
| Bronx    | 005         |       36005 |    10474 | Hunts Point and Mott Haven |
| Bronx    | 005         |       36005 |    10475 | Northeast Bronx            |
| Bronx    | 005         |       36005 |    10499 | NA                         |
| Bronx    | 005         |       36005 |    10550 | NA                         |
| Bronx    | 005         |       36005 |    10704 | NA                         |
| Bronx    | 005         |       36005 |    10705 | NA                         |
| Bronx    | 005         |       36005 |    10803 | NA                         |
| Kings    | 047         |       36047 |    11202 | NA                         |
| Kings    | 047         |       36047 |    11224 | Southern Brooklyn          |
| Kings    | 047         |       36047 |    11239 | Canarsie and Flatlands     |
| Kings    | 047         |       36047 |    11241 | NA                         |
| Kings    | 047         |       36047 |    11242 | NA                         |
| Kings    | 047         |       36047 |    11243 | NA                         |
| Kings    | 047         |       36047 |    11245 | NA                         |
| Kings    | 047         |       36047 |    11247 | NA                         |
| Kings    | 047         |       36047 |    11251 | NA                         |
| Kings    | 047         |       36047 |    11252 | NA                         |
| Kings    | 047         |       36047 |    11256 | NA                         |
| New York | 061         |       36061 |    10008 | NA                         |
| New York | 061         |       36061 |    10020 | Chelsea and Clinton        |
| New York | 061         |       36061 |    10041 | NA                         |
| New York | 061         |       36061 |    10043 | NA                         |
| New York | 061         |       36061 |    10045 | NA                         |
| New York | 061         |       36061 |    10047 | NA                         |
| New York | 061         |       36061 |    10048 | NA                         |
| New York | 061         |       36061 |    10055 | NA                         |
| New York | 061         |       36061 |    10072 | NA                         |
| New York | 061         |       36061 |    10080 | NA                         |
| New York | 061         |       36061 |    10081 | NA                         |
| New York | 061         |       36061 |    10082 | NA                         |
| New York | 061         |       36061 |    10087 | NA                         |
| New York | 061         |       36061 |    10101 | NA                         |
| New York | 061         |       36061 |    10102 | NA                         |
| New York | 061         |       36061 |    10103 | NA                         |
| New York | 061         |       36061 |    10104 | NA                         |
| New York | 061         |       36061 |    10105 | NA                         |
| New York | 061         |       36061 |    10106 | NA                         |
| New York | 061         |       36061 |    10107 | NA                         |
| New York | 061         |       36061 |    10108 | NA                         |
| New York | 061         |       36061 |    10109 | NA                         |
| New York | 061         |       36061 |    10110 | NA                         |
| New York | 061         |       36061 |    10111 | NA                         |
| New York | 061         |       36061 |    10112 | NA                         |
| New York | 061         |       36061 |    10113 | NA                         |
| New York | 061         |       36061 |    10114 | NA                         |
| New York | 061         |       36061 |    10115 | NA                         |
| New York | 061         |       36061 |    10116 | NA                         |
| New York | 061         |       36061 |    10117 | NA                         |
| New York | 061         |       36061 |    10118 | NA                         |
| New York | 061         |       36061 |    10119 | NA                         |
| New York | 061         |       36061 |    10120 | NA                         |
| New York | 061         |       36061 |    10121 | NA                         |
| New York | 061         |       36061 |    10122 | NA                         |
| New York | 061         |       36061 |    10123 | NA                         |
| New York | 061         |       36061 |    10124 | NA                         |
| New York | 061         |       36061 |    10125 | NA                         |
| New York | 061         |       36061 |    10126 | NA                         |
| New York | 061         |       36061 |    10129 | NA                         |
| New York | 061         |       36061 |    10130 | NA                         |
| New York | 061         |       36061 |    10131 | NA                         |
| New York | 061         |       36061 |    10132 | NA                         |
| New York | 061         |       36061 |    10133 | NA                         |
| New York | 061         |       36061 |    10138 | NA                         |
| New York | 061         |       36061 |    10149 | NA                         |
| New York | 061         |       36061 |    10150 | NA                         |
| New York | 061         |       36061 |    10151 | NA                         |
| New York | 061         |       36061 |    10152 | NA                         |
| New York | 061         |       36061 |    10153 | NA                         |
| New York | 061         |       36061 |    10154 | NA                         |
| New York | 061         |       36061 |    10155 | NA                         |
| New York | 061         |       36061 |    10156 | NA                         |
| New York | 061         |       36061 |    10157 | NA                         |
| New York | 061         |       36061 |    10158 | NA                         |
| New York | 061         |       36061 |    10159 | NA                         |
| New York | 061         |       36061 |    10160 | NA                         |
| New York | 061         |       36061 |    10161 | NA                         |
| New York | 061         |       36061 |    10163 | NA                         |
| New York | 061         |       36061 |    10164 | NA                         |
| New York | 061         |       36061 |    10165 | NA                         |
| New York | 061         |       36061 |    10166 | NA                         |
| New York | 061         |       36061 |    10167 | NA                         |
| New York | 061         |       36061 |    10168 | NA                         |
| New York | 061         |       36061 |    10169 | NA                         |
| New York | 061         |       36061 |    10170 | NA                         |
| New York | 061         |       36061 |    10171 | NA                         |
| New York | 061         |       36061 |    10172 | NA                         |
| New York | 061         |       36061 |    10173 | NA                         |
| New York | 061         |       36061 |    10174 | NA                         |
| New York | 061         |       36061 |    10175 | NA                         |
| New York | 061         |       36061 |    10176 | NA                         |
| New York | 061         |       36061 |    10177 | NA                         |
| New York | 061         |       36061 |    10178 | NA                         |
| New York | 061         |       36061 |    10179 | NA                         |
| New York | 061         |       36061 |    10185 | NA                         |
| New York | 061         |       36061 |    10197 | NA                         |
| New York | 061         |       36061 |    10199 | NA                         |
| New York | 061         |       36061 |    10213 | NA                         |
| New York | 061         |       36061 |    10242 | NA                         |
| New York | 061         |       36061 |    10249 | NA                         |
| New York | 061         |       36061 |    10256 | NA                         |
| New York | 061         |       36061 |    10259 | NA                         |
| New York | 061         |       36061 |    10260 | NA                         |
| New York | 061         |       36061 |    10261 | NA                         |
| New York | 061         |       36061 |    10265 | NA                         |
| New York | 061         |       36061 |    10268 | NA                         |
| New York | 061         |       36061 |    10269 | NA                         |
| New York | 061         |       36061 |    10270 | NA                         |
| New York | 061         |       36061 |    10271 | NA                         |
| New York | 061         |       36061 |    10272 | NA                         |
| New York | 061         |       36061 |    10273 | NA                         |
| New York | 061         |       36061 |    10274 | NA                         |
| New York | 061         |       36061 |    10275 | NA                         |
| New York | 061         |       36061 |    10276 | NA                         |
| New York | 061         |       36061 |    10277 | NA                         |
| New York | 061         |       36061 |    10278 | NA                         |
| New York | 061         |       36061 |    10279 | NA                         |
| New York | 061         |       36061 |    10281 | NA                         |
| New York | 061         |       36061 |    10285 | NA                         |
| New York | 061         |       36061 |    10286 | NA                         |
| New York | 061         |       36061 |    10292 | NA                         |
| Queens   | 081         |       36081 |    11001 | NA                         |
| Queens   | 081         |       36081 |    11004 | Southeast Queens           |
| Queens   | 081         |       36081 |    11005 | Southeast Queens           |
| Queens   | 081         |       36081 |    11040 | NA                         |
| Queens   | 081         |       36081 |    11096 | NA                         |
| Queens   | 081         |       36081 |    11351 | NA                         |
| Queens   | 081         |       36081 |    11352 | NA                         |
| Queens   | 081         |       36081 |    11359 | North Queens               |
| Queens   | 081         |       36081 |    11362 | Northeast Queens           |
| Queens   | 081         |       36081 |    11363 | Northeast Queens           |
| Queens   | 081         |       36081 |    11371 | NA                         |
| Queens   | 081         |       36081 |    11380 | NA                         |
| Queens   | 081         |       36081 |    11381 | NA                         |
| Queens   | 081         |       36081 |    11386 | NA                         |
| Queens   | 081         |       36081 |    11405 | NA                         |
| Queens   | 081         |       36081 |    11411 | Southeast Queens           |
| Queens   | 081         |       36081 |    11412 | Jamaica                    |
| Queens   | 081         |       36081 |    11413 | Southeast Queens           |
| Queens   | 081         |       36081 |    11414 | Southwest Queens           |
| Queens   | 081         |       36081 |    11416 | Southwest Queens           |
| Queens   | 081         |       36081 |    11417 | Southwest Queens           |
| Queens   | 081         |       36081 |    11419 | Southwest Queens           |
| Queens   | 081         |       36081 |    11420 | Southwest Queens           |
| Queens   | 081         |       36081 |    11421 | Southwest Queens           |
| Queens   | 081         |       36081 |    11422 | Southeast Queens           |
| Queens   | 081         |       36081 |    11423 | Jamaica                    |
| Queens   | 081         |       36081 |    11424 | NA                         |
| Queens   | 081         |       36081 |    11425 | NA                         |
| Queens   | 081         |       36081 |    11427 | Southeast Queens           |
| Queens   | 081         |       36081 |    11428 | Southeast Queens           |
| Queens   | 081         |       36081 |    11429 | Southeast Queens           |
| Queens   | 081         |       36081 |    11430 | NA                         |
| Queens   | 081         |       36081 |    11431 | NA                         |
| Queens   | 081         |       36081 |    11433 | Jamaica                    |
| Queens   | 081         |       36081 |    11436 | Jamaica                    |
| Queens   | 081         |       36081 |    11439 | NA                         |
| Queens   | 081         |       36081 |    11451 | NA                         |
| Queens   | 081         |       36081 |    11499 | NA                         |
| Queens   | 081         |       36081 |    11559 | NA                         |
| Queens   | 081         |       36081 |    11580 | NA                         |
| Queens   | 081         |       36081 |    11690 | NA                         |
| Queens   | 081         |       36081 |    11694 | Rockaways                  |
| Queens   | 081         |       36081 |    11695 | Rockaways                  |
| Queens   | 081         |       36081 |    11697 | Rockaways                  |
| Richmond | 085         |       36085 |    10302 | Port Richmond              |
| Richmond | 085         |       36085 |    10307 | South Shore                |
| Richmond | 085         |       36085 |    10309 | South Shore                |
| Richmond | 085         |       36085 |    10310 | Port Richmond              |
| Richmond | 085         |       36085 |    10311 | NA                         |
| Richmond | 085         |       36085 |    10313 | NA                         |

- 10278 - Government building, Jacob K Javits building has its own zip
  code, so no residential properties there for zillow.
- 10118 Empire state building has its own zip code.
- 10111: Rockefeller Center has it’s own zip code.

Some business/ government buildings or financial areas have their own
zip codes in New York, so there cannot be residential properties there
and therefore they wouldn’t show up on Zillow.

Make a table that shows the 10 ZIP codes (along with the borough and
neighborhood) with largest drop in price from January 2020 to 2021.
Comment.

``` r
january_data <- joined_zipcode_data |>
  filter(date == "x2020_01_31" | date == "x2021_01_31") |>
  select(county, zip_code, neighborhood, date, zori) |>
  pivot_wider(names_from = date, values_from = zori, 
              names_prefix = "zori_") |>
  filter(!is.na(zori_x2020_01_31) & !is.na(zori_x2021_01_31)) |>
  mutate(price_change = zori_x2021_01_31 - zori_x2020_01_31) |>
  arrange(price_change)

top_ten_changes <- january_data |>
  slice(1:10) |>
  rename(
    zori_2020 = zori_x2020_01_31,
    zori_2021 = zori_x2021_01_31
  ) |>
  select(zip_code, county, neighborhood, zori_2020, zori_2021, price_change)

kable(top_ten_changes)
```

| zip_code | county | neighborhood | zori_2020 | zori_2021 | price_change |
|---:|:---|:---|---:|---:|---:|
| 10007 | New York | Lower Manhattan | 6334.211 | 5421.614 | -912.5966 |
| 10069 | New York | NA | 4623.042 | 3874.918 | -748.1245 |
| 10009 | New York | Lower East Side | 3406.442 | 2692.187 | -714.2550 |
| 10016 | New York | Gramercy Park and Murray Hill | 3731.135 | 3019.431 | -711.7045 |
| 10001 | New York | Chelsea and Clinton | 4108.098 | 3397.648 | -710.4499 |
| 10002 | New York | Lower East Side | 3645.416 | 2935.113 | -710.3028 |
| 10004 | New York | Lower Manhattan | 3149.658 | 2443.697 | -705.9608 |
| 10038 | New York | Lower Manhattan | 3573.201 | 2875.616 | -697.5853 |
| 10012 | New York | Greenwich Village and Soho | 3628.566 | 2942.344 | -686.2218 |
| 10010 | New York | Gramercy Park and Murray Hill | 3697.284 | 3012.353 | -684.9304 |

Most of these are very expensive areas, but also very dense areas with
very little green space nearby. COVID-19 was probably the worst in these
neighborhoods (the most cases), a lot of people probably didn’t want to
live in a super dense neighborhood with a lot of cases and risk getting
sick, and without an outdoor space to be able to get fresh air, the rent
prices probably seemed very difficult to justify, so the landlords
probably had to shift their prices much lower to adjust for that to try
to convince people to rent in those areas despite covid.
